endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        size: 30
        margin: 1
        encoding: 'UTF-8'
        errorCorrectionLevel: 'low'
        roundBlockSizeMode: 'margin'
        validateResult: false
