App\Entity\User:
    constraints:
        - Callback: validate
App\Entity\Comercio:
    constraints:
        - Callback: validate
App\Entity\Producto:
    constraints:
        - Callback: validate
App\Entity\Oferta:
    constraints:
        - Callback: validate
App\Entity\ListaCompra:
    constraints:
        - Callback: validate
App\Entity\Voucher:
    constraints:
        - Callback: validate


